### ISSUE TITLE
Color for disabled checkboxes, radio buttons, and tabs

### ISSUE THREAD

**Issue by kyleuckert** [Michael-Yongshi/PyQt-Darktheme#3]
I noticed that when tabs, radio buttons, or checkboxes are disabled, the text color is the same as when they are enabled, making it difficult to distinguish between enabled/disabled widgets.

As a workaround, I defined the colors for these disabled widgets in the stylesheet after I set the pallet for the application:

```
view = QApplication(sys.argv)
view.setStyle('Fusion')
view.setPalette(DarkPalette())
view.setStyleSheet("QToolTip { color: #ffffff; background-color: grey; border: 1px solid white; }"
                   "QCheckBox:disabled {color:#191919;}"
                   "QRadioButton:disabled {color:#191919;}"
                   "QWidget:disabled {color:#191919;}")
```

**Comment by Michael-Yongshi** [comment]
Added your proposal to the set up of the DarkApplication class
Thanks for your suggestion! :)

**Comment by Michael-Yongshi** [comment]
Also added to the DarkPalette class now, to align with the use of the other colours
