### ISSUE TITLE
Any plan for supporting PyQt6?

### ISSUE THREAD

**Issue by ribeaud** [Michael-Yongshi/PyQt-Darktheme#7]
Hi. I wanted to give it a try in our application already migrated to https://pypi.org/project/PyQt6/. However, it does not seem to work.

Or maybe _dark mode_ is implemented out-of-the-box in **PyQt6** and this library is no longer needed?

Kind regards,

christian

**Comment by Michael-Yongshi** [comment]
Im not working with PyQt6 yet, so I still need to look into it.

But if it has a dark theme that does mainly already what im doing here then I may not port it unless I can offer some worthwile features.

this repo also has some widgets that are clickable and some decorators that may be useful in PyQt6, but I may fork that part in a seperate repo then if im not porting the dark theme as well as they are not really tied to the 'theme' functionality

**Comment by Michael-Yongshi** [comment]
supported pyqt6 already a while ago
